---

- name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords"
  ansible.builtin.win_security_policy:
      section: System Access
      key: passwordhistorysize
      value: "{{ win22cis_passwordhistorysize }}"
  when:
      - rule_1_1_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.1
      - automated
      - passwords

- name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0"
  ansible.builtin.win_security_policy:
      section: System Access
      key: MaximumPasswordAge
      value: "{{ win22cis_maximumpasswordage }}"
  when:
      - rule_1_1_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.2
      - automated
      - passwords

- name: "1.1.3 | PATCH | Ensure Minimum password age is set to 1 or more days"
  ansible.builtin.win_security_policy:
      section: System Access
      key: MinimumPasswordAge
      value: "{{ win22cis_minimumpasswordage }}"
  when:
      - rule_1_1_3
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.3
      - automated
      - passwords

- name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters"
  ansible.builtin.win_security_policy:
      section: System Access
      key: MinimumPasswordLength
      value: "{{ win22cis_minimumpasswordlength }}"
  when:
      - rule_1_1_4
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.4
      - automated
      - passwords

- name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled"
  ansible.builtin.win_security_policy:
      section: System Access
      key: PasswordComplexity
      value: 1
  when:
      - rule_1_1_5
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.5
      - automated
      - passwords

- name: "1.1.6 | PATCH | Ensure Relax minimum password length limits is set to enabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\SAM
      name: RelaxMinimumPasswordLengthLimits
      data: 1
      type: dword
  when:
      - rule_1_1_6
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.6
      - automated
      - passwords

- name: "1.1.7 | PATCH | Ensure Store passwords using reversible encryption is set to Disabled"
  ansible.builtin.win_security_policy:
      section: System Access
      key: ClearTextPassword
      value: "0"
  when:
      - rule_1_1_7
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.1.7
      - automated
      - passwords

# This rule must be applied first to make rule_1.2.1 and rule_1.2.3 applicable
- name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempts but not 0"
  ansible.builtin.win_security_policy:
      section: System Access
      key: LockoutBadCount
      value: "{{ win22cis_lockoutbadcount }}"
  when:
      - rule_1_2_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.2.2
      - automated
      - account
      
- name: "1.2.3 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes"
  ansible.builtin.win_security_policy:
      section: System Access
      key: ResetLockoutCount
      value: "{{ win22cis_resetlockoutcount }}"
  when:
      - rule_1_2_3
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.2.3
      - automated
      - account
      
# Speelman | added because of this error "Failed to import secedit.ini file from C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmp81F3.tmp
- name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes"
  ansible.builtin.win_security_policy:
      section: System Access
      key: LockoutDuration
      value: "{{ win22cis_lockoutduration }}"
  when:
      - rule_1_2_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_1.2.1
      - automated
      - account


